"use client";

import React, { useState, useEffect } from "react";
import { useParams, useRouter } from "next/navigation";
import Link from "next/link";
import { AppLayout } from "@/components/layout/AppLayout";
import { getModuleById, getBusinessRules } from "@/lib/api";
import { Module, BusinessRule } from "@/lib/types";
import { RiskBadge } from "@/components/ui/RiskBadge";
import { StatusBadge } from "@/components/ui/StatusBadge";
import { SeverityBadge } from "@/components/ui/SeverityBadge";
import { RiskGauge } from "@/components/ui/RiskGauge";
import { RuleCard } from "@/components/ui/RuleCard";
import { useToast } from "@/components/ui/ToastContext";
import {
  Code2,
  FileText,
  Sparkles,
  ShieldAlert,
  Layers,
  ArrowLeft,
  ArrowRight,
  GitFork,
  CheckCircle2,
  AlertTriangle,
  Lightbulb,
  Download,
  Copy,
  Check,
  Zap,
  Terminal,
} from "lucide-react";

export default function ModuleDetailPage() {
  const params = useParams();
  const router = useRouter();
  const { toast } = useToast();

  const moduleId = params?.id as string;
  const [module, setModule] = useState<Module | null>(null);
  const [rules, setRules] = useState<BusinessRule[]>([]);
  const [loading, setLoading] = useState(true);
  const [activeTab, setActiveTab] = useState<"overview" | "code" | "rules" | "insights">("overview");
  const [selectedIssueLine, setSelectedIssueLine] = useState<number | null>(null);

  useEffect(() => {
    async function loadModule() {
      if (!moduleId) return;
      try {
        const [modData, rulesData] = await Promise.all([
          getModuleById(moduleId),
          getBusinessRules(moduleId),
        ]);
        setModule(modData);
        setRules(rulesData);
      } catch (err) {
        console.error("Failed to load module", err);
      } finally {
        setLoading(false);
      }
    }
    loadModule();
  }, [moduleId]);

  const handleExportAllRules = () => {
    const markdownContent = `# Business Rules Spec: ${module?.name}\n\nGenerated by ReCore AI AST Decompiler\n\n` +
      rules.map((r, i) => `## Rule ${i + 1}: ${r.plainEnglish}\n- **Line:** ${r.line}\n- **Confidence:** ${r.confidence}%\n- **Category:** ${r.category || 'General'}\n\n\`\`\`python\n${r.codeSnippet}\n\`\`\`\n\n*Implication:* ${r.implication || 'N/A'}\n`).join("\n\n---\n\n");

    const blob = new Blob([markdownContent], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${module?.name || 'module'}_business_rules_spec.md`;
    a.click();
    URL.revokeObjectURL(url);

    toast.success("Spec Exported", `Downloaded business rules for ${module?.name}`);
  };

  if (loading) {
    return (
      <AppLayout>
        <div className="space-y-6 animate-pulse">
          <div className="h-6 w-32 bg-slate-800 rounded" />
          <div className="h-12 w-96 bg-slate-800 rounded" />
          <div className="h-96 bg-slate-900 rounded-2xl border border-slate-800" />
        </div>
      </AppLayout>
    );
  }

  if (!module) {
    return (
      <AppLayout>
        <div className="text-center py-16 space-y-4">
          <AlertTriangle className="w-12 h-12 text-rose-400 mx-auto" />
          <h2 className="text-xl font-bold text-white">Module Not Found</h2>
          <p className="text-xs text-slate-400">
            Could not locate module ID &quot;{moduleId}&quot; in the current repository analysis.
          </p>
          <Link
            href="/"
            className="inline-flex items-center gap-2 px-4 py-2 rounded-xl bg-slate-800 text-white text-xs font-semibold"
          >
            <ArrowLeft className="w-4 h-4" />
            Back to Dashboard
          </Link>
        </div>
      </AppLayout>
    );
  }

  const rawCodeLines = (module.rawCode || "").split("\n");
  const issueLinesSet = new Set(module.issues.map((i) => i.line));

  return (
    <AppLayout>
      <div className="space-y-6">
        {/* Navigation Breadcrumb & Actions */}
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 pb-4 border-b border-slate-800">
          <div>
            <div className="flex items-center gap-2 text-xs text-slate-400 mb-1">
              <Link href="/" className="hover:text-cyan-400 transition-colors">
                Modules
              </Link>
              <span>/</span>
              <span className="font-mono text-slate-200">{module.path}</span>
            </div>

            <div className="flex items-center gap-3">
              <h1 className="text-2xl font-bold font-mono tracking-tight text-white">
                {module.name}
              </h1>
              <StatusBadge status={module.status} />
              <RiskBadge level={module.riskLevel} score={module.riskScore} />
            </div>
          </div>

          <div className="flex items-center gap-3">
            <Link
              href={`/graph`}
              className="flex items-center gap-2 px-3.5 py-2 rounded-xl bg-slate-900 hover:bg-slate-800 text-slate-300 hover:text-white text-xs font-semibold border border-slate-800 transition-colors"
            >
              <GitFork className="w-3.5 h-3.5 text-cyan-400" />
              Blast Radius
            </Link>

            <Link
              href={`/validate/${module.id}`}
              className="flex items-center gap-2 px-4 py-2 rounded-xl bg-gradient-to-r from-cyan-500 to-indigo-600 hover:from-cyan-400 hover:to-indigo-500 text-slate-950 font-bold text-xs transition-all shadow-lg shadow-cyan-500/20"
            >
              <Sparkles className="w-3.5 h-3.5 fill-current" />
              Modernize This Module
              <ArrowRight className="w-3.5 h-3.5" />
            </Link>
          </div>
        </div>

        {/* Tab Navigation */}
        <div className="flex items-center gap-2 p-1 rounded-2xl bg-slate-900/80 border border-slate-800 text-xs font-medium overflow-x-auto">
          {[
            { id: "overview", label: "Overview & Issues", icon: Layers, count: module.issues.length },
            { id: "code", label: "AST Code Inspection", icon: Code2, count: `${module.loc} LOC` },
            { id: "rules", label: "Business Rule Extractor", icon: Sparkles, count: `${rules.length} Rules` },
            { id: "insights", label: "AI Diagnostic Insights", icon: Lightbulb },
          ].map((tab) => {
            const Icon = tab.icon;
            const isActive = activeTab === tab.id;
            return (
              <button
                key={tab.id}
                onClick={() => setActiveTab(tab.id as typeof activeTab)}
                className={`flex items-center gap-2 px-4 py-2 rounded-xl transition-all shrink-0 ${
                  isActive
                    ? "bg-slate-800 text-white font-bold shadow-sm border border-slate-700"
                    : "text-slate-400 hover:text-slate-200 hover:bg-slate-900"
                }`}
              >
                <Icon className={`w-3.5 h-3.5 ${isActive ? "text-cyan-400" : "text-slate-500"}`} />
                <span>{tab.label}</span>
                {tab.count && (
                  <span
                    className={`text-[10px] font-mono px-1.5 py-0.5 rounded ${
                      isActive
                        ? "bg-cyan-950 text-cyan-300 border border-cyan-500/30"
                        : "bg-slate-950 text-slate-500"
                    }`}
                  >
                    {tab.count}
                  </span>
                )}
              </button>
            );
          })}
        </div>

        {/* TAB 1: OVERVIEW */}
        {activeTab === "overview" && (
          <div className="space-y-6">
            {/* Top Overview Cards */}
            <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
              {/* Risk Gauge Card */}
              <div className="lg:col-span-4 p-6 rounded-2xl bg-slate-900/60 border border-slate-800 flex flex-col items-center justify-center text-center">
                <RiskGauge
                  score={module.riskScore}
                  level={module.riskLevel}
                  size={150}
                  strokeWidth={12}
                />
                <p className="text-xs text-slate-400 mt-4 leading-relaxed max-w-xs">
                  Composite score evaluated from security vulnerability severities, lack of test assertions, and cyclomatic branching depth.
                </p>
              </div>

              {/* Module Metadata Breakdown */}
              <div className="lg:col-span-8 p-6 rounded-2xl bg-slate-900/60 border border-slate-800 flex flex-col justify-between">
                <div>
                  <h3 className="text-sm font-bold text-white mb-2">Module Architecture Summary</h3>
                  <p className="text-xs text-slate-300 leading-relaxed mb-5">
                    {module.summary}
                  </p>

                  <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 p-4 rounded-xl bg-slate-950/80 border border-slate-800 text-xs font-mono">
                    <div>
                      <span className="text-slate-500 block text-[10px] uppercase">Lines of Code</span>
                      <span className="text-base font-bold text-white">{module.loc} LOC</span>
                    </div>
                    <div>
                      <span className="text-slate-500 block text-[10px] uppercase">Cyclomatic Complexity</span>
                      <span className="text-base font-bold text-rose-400">{module.complexity}</span>
                    </div>
                    <div>
                      <span className="text-slate-500 block text-[10px] uppercase">Unit Test Coverage</span>
                      <span className="text-base font-bold text-amber-400">{module.testCoverage || 0}%</span>
                    </div>
                    <div>
                      <span className="text-slate-500 block text-[10px] uppercase">Downstream Dependents</span>
                      <span className="text-base font-bold text-cyan-400">{module.usedBy.length} modules</span>
                    </div>
                  </div>
                </div>

                <div className="pt-4 border-t border-slate-800 flex flex-wrap items-center justify-between gap-3 text-xs">
                  <div className="flex items-center gap-2">
                    <span className="text-slate-500">Depends on:</span>
                    {module.dependsOn.length > 0 ? (
                      module.dependsOn.map((dep) => (
                        <Link
                          key={dep}
                          href={`/module/${dep}`}
                          className="px-2 py-0.5 rounded bg-slate-800 hover:bg-slate-700 text-cyan-300 font-mono text-[11px] border border-slate-700"
                        >
                          {dep}.py
                        </Link>
                      ))
                    ) : (
                      <span className="text-slate-500 font-mono">None (Base root)</span>
                    )}
                  </div>

                  <span className="text-slate-500 font-mono text-[11px]">
                    Last Analyzed: {new Date(module.lastAnalyzed || "").toLocaleDateString()}
                  </span>
                </div>
              </div>
            </div>

            {/* Discovered Issues List */}
            <div className="space-y-4">
              <div className="flex items-center justify-between">
                <div>
                  <h3 className="text-base font-bold text-white flex items-center gap-2">
                    <ShieldAlert className="w-5 h-5 text-rose-400" />
                    Detected Security & Code Smells ({module.issues.length})
                  </h3>
                  <p className="text-xs text-slate-400">
                    Pinpointed issues with source code lines and recommended remediations.
                  </p>
                </div>
              </div>

              <div className="space-y-3">
                {module.issues.map((issue) => (
                  <div
                    key={issue.id}
                    className="p-5 rounded-2xl bg-slate-900/70 border border-slate-800 hover:border-slate-700 transition-all space-y-3"
                  >
                    <div className="flex flex-wrap items-start justify-between gap-2">
                      <div className="flex items-center gap-2.5">
                        <SeverityBadge type={issue.type} severity={issue.severity} />
                        <span className="font-mono text-xs text-cyan-400 font-bold">
                          Line {issue.line}
                        </span>
                        {issue.cwe && (
                          <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-slate-800 text-slate-400 border border-slate-700">
                            {issue.cwe}
                          </span>
                        )}
                      </div>
                      <span className="text-xs font-mono text-slate-500">{issue.id}</span>
                    </div>

                    <p className="text-xs text-slate-200 font-medium leading-relaxed">
                      {issue.description}
                    </p>

                    {issue.snippet && (
                      <div className="p-3 rounded-xl bg-slate-950 border border-slate-800/90 font-mono text-xs text-rose-300 overflow-x-auto">
                        <pre>{issue.snippet}</pre>
                      </div>
                    )}

                    {issue.remediation && (
                      <div className="flex items-start gap-2 p-3 rounded-xl bg-emerald-950/20 border border-emerald-500/20 text-xs text-emerald-300">
                        <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0 mt-0.5" />
                        <div>
                          <strong>Remediation Strategy:</strong> {issue.remediation}
                        </div>
                      </div>
                    )}
                  </div>
                ))}
              </div>
            </div>
          </div>
        )}

        {/* TAB 2: AST CODE INSPECTION */}
        {activeTab === "code" && (
          <div className="rounded-2xl border border-slate-800 bg-slate-950 overflow-hidden shadow-2xl">
            <div className="flex items-center justify-between px-5 py-3 bg-slate-900 border-b border-slate-800">
              <div className="flex items-center gap-3">
                <Terminal className="w-4 h-4 text-cyan-400" />
                <span className="font-mono text-xs font-bold text-white">{module.path}</span>
                <span className="text-xs text-slate-400">({rawCodeLines.length} lines)</span>
              </div>
              <div className="flex items-center gap-2 text-xs font-mono text-slate-400">
                <span className="w-2.5 h-2.5 rounded-full bg-rose-500 inline-block" />
                <span>Highlighted Issue Lines</span>
              </div>
            </div>

            <div className="p-4 font-mono text-xs overflow-x-auto max-h-[620px]">
              {rawCodeLines.map((line, idx) => {
                const lineNum = idx + 1;
                const matchingIssue = module.issues.find((i) => i.line === lineNum);

                return (
                  <div
                    key={`line-${lineNum}`}
                    onClick={() => matchingIssue && setSelectedIssueLine(lineNum)}
                    className={`flex items-start gap-4 py-0.5 px-2 rounded transition-colors ${
                      matchingIssue
                        ? "bg-rose-950/50 text-rose-200 border-l-2 border-rose-500 cursor-pointer"
                        : "text-slate-300 hover:bg-slate-900/40"
                    }`}
                  >
                    <span className="w-8 text-right select-none text-slate-600 font-mono text-[11px]">
                      {lineNum}
                    </span>
                    <pre className="font-mono whitespace-pre-wrap break-all flex-1">{line || " "}</pre>
                    {matchingIssue && (
                      <span className="text-[10px] uppercase font-bold text-rose-400 shrink-0 bg-rose-500/20 px-2 py-0.5 rounded border border-rose-500/30">
                        {matchingIssue.type.replace("_", " ")}
                      </span>
                    )}
                  </div>
                );
              })}
            </div>
          </div>
        )}

        {/* TAB 3: BUSINESS RULE EXTRACTOR */}
        {activeTab === "rules" && (
          <div className="space-y-6">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 p-5 rounded-2xl bg-gradient-to-br from-slate-900 to-indigo-950/40 border border-indigo-500/30">
              <div>
                <div className="inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-full text-xs font-mono font-bold bg-cyan-500/10 text-cyan-300 border border-cyan-500/30 mb-2">
                  <Sparkles className="w-3.5 h-3.5 text-cyan-400" />
                  AI AST Decompiler
                </div>
                <h3 className="text-base font-bold text-white">
                  Extracted Hidden Business Rules & Invariants
                </h3>
                <p className="text-xs text-slate-300 mt-1 max-w-xl">
                  These business rules were extracted directly from AST branching heuristics. They represent essential business behavior that must not be broken during modernization.
                </p>
              </div>

              <button
                onClick={handleExportAllRules}
                className="flex items-center gap-2 px-4 py-2.5 rounded-xl bg-cyan-500 hover:bg-cyan-400 text-slate-950 font-bold text-xs transition-all shadow-lg shadow-cyan-500/20 shrink-0"
              >
                <Download className="w-3.5 h-3.5" />
                Export as Spec (.md)
              </button>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {rules.length > 0 ? (
                rules.map((rule) => (
                  <RuleCard
                    key={rule.id}
                    rule={rule}
                    onExportSpec={(r) => {
                      navigator.clipboard.writeText(
                        `### Rule ${r.id}: ${r.plainEnglish}\n\nCode snippet (Line ${r.line}):\n\`\`\`python\n${r.codeSnippet}\n\`\`\``
                      );
                      toast.success("Spec Copied", `Copied spec for ${r.id}`);
                    }}
                  />
                ))
              ) : (
                <div className="col-span-2 p-8 text-center rounded-2xl bg-slate-900/50 border border-slate-800 text-slate-400 text-xs">
                  No hidden domain rules flagged for this utility module.
                </div>
              )}
            </div>
          </div>
        )}

        {/* TAB 4: AI INSIGHTS */}
        {activeTab === "insights" && (
          <div className="space-y-6">
            <div className="p-6 rounded-2xl bg-slate-900/60 border border-slate-800 space-y-5">
              <div>
                <span className="text-[10px] font-bold uppercase tracking-wider text-cyan-400 font-mono">
                  Explainable AI Diagnostics
                </span>
                <h3 className="text-lg font-bold text-white mt-1">Why is this module risky?</h3>
                <p className="text-xs text-slate-300 leading-relaxed mt-2 p-4 rounded-xl bg-slate-950/80 border border-slate-800">
                  {module.aiExplanation}
                </p>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4 pt-3">
                <div className="p-4 rounded-xl bg-slate-950 border border-slate-800">
                  <span className="text-[10px] font-bold uppercase tracking-wider text-purple-400 font-mono">
                    Modernization Target Stack
                  </span>
                  <p className="text-sm font-bold text-white font-mono mt-1">
                    {module.targetStack}
                  </p>
                  <p className="text-xs text-slate-400 mt-2">
                    Guarantees async I/O throughput, strict Pydantic v2 data boundary validation, and zero SQL injection surfaces.
                  </p>
                </div>

                <div className="p-4 rounded-xl bg-slate-950 border border-slate-800">
                  <span className="text-[10px] font-bold uppercase tracking-wider text-emerald-400 font-mono">
                    Recommended Refactoring Path
                  </span>
                  <p className="text-xs text-slate-200 mt-1 leading-relaxed">
                    {module.modernizationRecommendation}
                  </p>
                </div>
              </div>

              <div className="pt-4 border-t border-slate-800 flex justify-end">
                <Link
                  href={`/validate/${module.id}`}
                  className="flex items-center gap-2 px-5 py-2.5 rounded-xl bg-cyan-500 hover:bg-cyan-400 text-slate-950 font-bold text-xs transition-all shadow-lg shadow-cyan-500/20"
                >
                  <Sparkles className="w-4 h-4" />
                  Launch Automated Synthesis & Validation
                  <ArrowRight className="w-4 h-4" />
                </Link>
              </div>
            </div>
          </div>
        )}
      </div>
    </AppLayout>
  );
}
